platform :ios, '7.0'
target ‘MVC框架’ do
#    网络请求
    pod 'AFNetworking', '~> 3.0'
#    ssl协议
    pod 'OpenSSL', '~> 1.0.208'
    
    pod 'pop' , '~>1.0.9'

#    图片加载
pod 'SDWebImage', '~>3.7.6'
##    键盘管理
#pod 'IQKeyboardManager' , '~>3.3.7'
##    提示视图
#pod 'MBProgressHUD', '~> 0.9.2'
#pod 'SVProgressHUD' , '~>2.1.2'
##    自动布局
#pod 'Masonry', '~>1.0.2'
##    刷新控件
#pod 'MJRefresh' , '~>3.1.0'
##    模型
#pod 'MJExtension' , '~>3.0.10'
##    本地数据库
#pod 'FMDB/common' , '~>2.5'
#pod 'FMDB/SQLCipher', '~>2.5'





#    测试工具
    pod 'FLEX', '~> 2.0', :configurations => ['Debug']



end
